### PR TITLE
Group report by location 

### PR DESCRIPTION
**Pull request by d22**
This pull request adds the possibility to group the report by location (one page per location). There is a toggle to enable/disable the feature in the app configuration.

The pull request contains also dependency updates, and the update to Node 16 and the CloudApp CLI 1.4.0. I hope it's oke to combine maintenance and features in one PR. 

I hope you consider merging this feature, it would be of great use for our institution.

### CODE REVIEW

**Comment by d22** [comment]
Please note: 
- The newest CloudApp CLI must be installed (1.4.0), in a Node 16.x.x NPM 7.x.x environment (`npm install -g @exlibris/exl-cloudapp-cli`)
- If `npm install` fails, please remove your 'node_modules' dir.
- If you can't login to your Alma instance via the CloudApp proxy, see https://github.com/ExLibrisGroup/cloudapp-sdk/issues/48

**Review by SydneyUni-Jim — APPROVED** [review]

**Comment by SydneyUni-Jim** [comment]
Hi @d22.

Thanks for this. I'll merge it in and published version 2021.2. The second production release. 🎉 

Yeah, it would have been better for this have been two pull requests. It's best if a pull request is for a single discreet update.

**Comment by d22** [comment]
Hi @SydneyUni-Jim, thank you for your fast reaction, and the release!

**Comment by d22** [comment]
Hi @SydneyUni-Jim 
Please excuse me for asking here: Although you have released the CloudApp, it is not yet available in Alma. Is this usual, do I just have to wait longer, or are further steps necessary? 
Thank you very much for your help!
BR Jonas

**Comment by SydneyUni-Jim** [comment]
Hi @d22. It should have appeared within an hour or two. I checked that «eca build» is succeeding and I checked that webhook did deliver. 

I've updated the release message, which triggered antoher webhook delivery.

For the record, here's the output of «eca build». I don't think those warnings fail the build.

```
❯ eca build
⠸ Building...- Copying assets...
⠼ Building...✔ Copying assets complete.
- Generating index html...
✔ Index html generation complete.
Warning: /Users/jim/Documents/Development/alma/print-slip-report/.ng/src/app/requested-resources/user-enrichment-service.ts depends on 'lru-cache'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /Users/jim/Documents/Development/alma/print-slip-report/.ng/src/app/download-excel-slip-report/download-excel-slip-report.service.ts depends on 'file-saver'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /Users/jim/Documents/Development/alma/print-slip-report/.ng/src/app/download-excel-slip-report/download-excel-slip-report.service.ts depends on 'sheetjs-style'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Generated 13 files in 91932ms

./build/3rdpartylicenses.txt
./build/6.418f2f23707d6061258d.js
./build/7.dc4f016225802866a539.js
./build/8.8bd8332b5fff329719a7.js
./build/assets
./build/common.f16638686c3ce4a3c360.js
./build/favicon.ico
./build/index.html
./build/main.8fc6547b5b48bc7b5071.js
./build/polyfills-es5.3e8da80aed2998379907.js
./build/polyfills.f8d154fd8764f8f5e8a8.js
./build/runtime.e508668c94b2fcc1f76b.js
./build/styles.6f1f42a3248b9109c57b.css
```

**Comment by SydneyUni-Jim** [comment]
Tracking why it's not deploying over at https://developers.exlibrisgroup.com/?post_type=topic&p=71899

**Comment by d22** [comment]
Hi @SydneyUni-Jim, thank you for taking action, but sadly, the new release is still not available, it seems to be an Issue on ExLibris side (maybe @jweisman can help). Should I create a forum post?

**Comment by SydneyUni-Jim** [comment]
I did a forum post, but it's not appearing. I'm guessing it's held up in moderation.

**Comment by jweisman** [comment]
Hi - you can check the forum post on the Dev Network. 
https://developers.exlibrisgroup.com/forums/topic/print-slips-report-v2021-2-0-not-deploying/

**Comment by SydneyUni-Jim** [comment]
@d22 Version 2021.2.1 is published and has landed.

**Pull request merged**
